Repository managemeproject/Manage-Me, pull requests merged in 2018-08, with the labels that each got.

#13 removed duplicate constant
  src/main/resources/config/liquibase/authorities.csv
Labels: bug

#20 Remove entity duplicates from menu
  src/main/webapp/app/layouts/navbar/navbar.component.html
Labels: enhancement

#22 Removed entities from Reg Employee nav bar.
  src/main/java/com/manageme/app/web/rest/DepartmentResource.java
  src/main/java/com/manageme/app/web/rest/EmployeeResource.java
  src/main/java/com/manageme/app/web/rest/LineItemResource.java
  src/main/webapp/app/layouts/navbar/navbar.component.html
Labels: enhancement

#38 Approve line item by employee
  src/main/webapp/app/entities/separation-application/separation-application-detail.component.html
  src/main/webapp/app/entities/separation-application/separation-application-update.component.html
  src/main/webapp/app/entities/separation-application/separation-application.component.html
  src/main/webapp/app/entities/separation-application/separation-application.component.ts
  src/main/webapp/app/vendor.ts
Labels: ui

#50 Add line items to Separation Application while logged on as Functional Rep.
  src/main/webapp/app/entities/separation-application/separation-application-update.component.html
  src/main/webapp/app/entities/separation-application/separation-application-update.component.ts
Labels: enhancement
